language: node_js
node_js: 10
cache: npm

script:
  - node -v
  - npm -v
  - npm install -g nodeppt
  - nodeppt build slides/00_ppt_template.md

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master
